version: '2'
services:
  saloodo:
    build: .
    ports:
      - 81:80
    volumes:
      - ./:/var/www
      - ./docker/logs/:/var/log
    env_file:
      - ./.env
    container_name: saloodo
    depends_on:
      - mysqlstore

  mysqlstore:
    image: mysql:5.7
    container_name: mysqlstore
    environment:
      # with mysql
      MYSQL_DATABASE: saloodo
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
